version: '3.7' 

services:
  mydevubuntu:
    image: mydev/ubuntu:1.0.0
    container_name: mydevubuntu
    ports: 
      - "2222:22"
      - "2223:2223"
    networks:
      # create the docker network first: docker network create local_default_network
      - local_default_network
      # create the docker network first: docker network create pp_service_network
      - pp_service_network
    volumes:
      - /System/Volumes/Data/Software/Project/pipi:/System/Volumes/Data/Software/Project/pipi
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    command:
      bash -c "/etc/init.d/ssh restart && tail -f /dev/null"

networks:
  local_default_network:
    external: true
  pp_service_network:
    external: true